src/objects/Relay__c.object
<CustomObject>
    <label>Relay</label>
    <nameField>
        <label>Relay Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RelaySwitch__c.object
<CustomObject>
    <fields>
        <fullName>Relay__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relay</label>
        <referenceTo>Relay__c</referenceTo>
        <relationshipLabel>RelaySwitches</relationshipLabel>
        <relationshipName>RelaySwitches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POWER OFF</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>POWER ON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RelaySwitch</label>
    <nameField>
        <label>RelaySwitch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RelaySwitches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SwitchLog__c.object
<CustomObject>
    <fields>
        <fullName>ActionAtStateStart__c</fullName>
        <label>ActionAtStateStart</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POWER OFF</fullName>
                </value>
                <value>
                    <fullName>POWER ON</fullName>
                </value>
                <value>
                    <fullName>NETWORK FAILURE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelaySwitch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelaySwitch</label>
        <referenceTo>RelaySwitch__c</referenceTo>
        <relationshipLabel>SwitchLogs</relationshipLabel>
        <relationshipName>SwitchLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StateStartTime__c</fullName>
        <label>StateStartTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StateStopTime__c</fullName>
        <label>StateStopTime</label>
        <type>DateTime</type>
    </fields>
    <label>SwitchLog</label>
    <nameField>
        <displayFormat>SW-LG-{0000000}</displayFormat>
        <label>SwitchLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SwitchLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RelayTriggerHandler.cls
public class RelayTriggerHandler {
    public static void createLogEventForNetworkOutageStart(List<Relay__c> toggledRelays)
    {
        List<SwitchLog__c> newRecords = new List<SwitchLog__c>();
        for(Relay__c relayToggled : toggledRelays )
        {
            List<SwitchLog__c> previousRecords = [SELECT Id, StateStartTime__c, StateStopTime__c, 
                                                  RelaySwitch__c,RelaySwitch__r.Relay__c, ActionAtStateStart__c FROM SwitchLog__c
                                                  where RelaySwitch__r.Relay__c=:relayToggled.Id and StateStopTime__c=null];
            Datetime currentInstance = System.now();
            for(SwitchLog__c log : previousRecords)
            {
                log.StateStopTime__c=currentInstance;
                SwitchLog__c logRecord = new SwitchLog__c(
                StateStartTime__c=currentInstance,RelaySwitch__c=log.RelaySwitch__c, ActionAtStateStart__c='NETWORK FAILURE');
                newRecords.add(logRecord);
            }
            update previousRecords;
        }
        insert newRecords;
    }
    
    public static void createLogEventForNetworkOutageEnd(List<RelaySwitch__c> toggledRelaySwitches)
    {
        Set<Id> recoveredSwithchesId = new Set<Id>();
        for(RelaySwitch__c sw:toggledRelaySwitches)
        {
            recoveredSwithchesId.add(sw.Id);
        }
        List<SwitchLog__c> newRecords = new List<SwitchLog__c>();
        List<SwitchLog__c> previousRecords = [SELECT Id, StateStartTime__c, StateStopTime__c, 
                                                  RelaySwitch__c,RelaySwitch__r.Relay__c ,RelaySwitch__r.Status__c, ActionAtStateStart__c FROM SwitchLog__c
                                                  where RelaySwitch__c IN  :recoveredSwithchesId and StateStopTime__c=null and 
                                                 ActionAtStateStart__c='NETWORK FAILURE' ];
            Datetime currentInstance = System.now();
            for(SwitchLog__c log : previousRecords)
            {
                log.StateStopTime__c=currentInstance;
                SwitchLog__c logRecord = new SwitchLog__c(
                StateStartTime__c=currentInstance,RelaySwitch__c=log.RelaySwitch__c, ActionAtStateStart__c=log.RelaySwitch__r.Status__c);
                newRecords.add(logRecord);
            }
            update previousRecords;
        insert newRecords;
        }
        
        
    }