src/objects/RelaySwitch__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POWER OFF</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>POWER ON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RelaySwitch</label>
    <nameField>
        <label>RelaySwitch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RelaySwitches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SwitchLog__c.object
<CustomObject>
    <fields>
        <fullName>ActionAtStateStart__c</fullName>
        <label>ActionAtStateStart</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POWER OFF</fullName>
                </value>
                <value>
                    <fullName>POWER ON</fullName>
                </value>
                <value>
                    <fullName>NETWORK FAILURE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RelaySwitch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelaySwitch</label>
        <referenceTo>RelaySwitch__c</referenceTo>
        <relationshipLabel>SwitchLogs</relationshipLabel>
        <relationshipName>SwitchLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StateStartTime__c</fullName>
        <label>StateStartTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StateStopTime__c</fullName>
        <label>StateStopTime</label>
        <type>DateTime</type>
    </fields>
    <label>SwitchLog</label>
    <nameField>
        <displayFormat>SW-LG-{0000000}</displayFormat>
        <label>SwitchLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SwitchLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RelaySwitchTriggerHandler.cls
public class RelaySwitchTriggerHandler {
    
    /**
     * This method is to be used in case of normal switching without any power outage occurring.
     * 
     */
    public static void createLogEvent(List<RelaySwitch__c> toggledSwitches)
    {
        List<SwitchLog__c> newRecords = new List<SwitchLog__c>();
        for(RelaySwitch__c switchToggled : toggledSwitches )
        {
            List<SwitchLog__c> previousRecords = [SELECT Id, StateStartTime__c, StateStopTime__c, 
                                                  RelaySwitch__c, ActionAtStateStart__c FROM SwitchLog__c
                                                  where RelaySwitch__c=:switchToggled.Id and StateStopTime__c=null];
            Datetime currentInstance = System.now();
            if(previousRecords.size()>1)// Exception Scenario . Handle here
            {
                
            }
            else if(previousRecords.size()==1) // Normal scenario after first usage
            {
                
                previousRecords[0].StateStopTime__c=currentInstance;
                update previousRecords;// Using update withing loop is probably not a good idea. Bulkify the functionality later.
                
            }
            
            SwitchLog__c logRecord = new SwitchLog__c(
                StateStartTime__c=currentInstance,RelaySwitch__c=switchToggled.Id, ActionAtStateStart__c=switchToggled.Status__c);
            newRecords.add(logRecord);
            
        }
        insert newRecords;
        
    }
    
    
}