src/objects/Room__c.object
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Switch__c.object
<CustomObject>
    <description>This is the unit from which all operations will be controlled</description>
    <fields>
        <fullName>Room__c</fullName>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Switch</relationshipLabel>
        <relationshipName>Switch</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wattage__c</fullName>
        <description>Input for the wattage of the associated instrument with this switch</description>
        <label>Wattage</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isSwitchedOn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSwitchedOn</label>
        <type>Checkbox</type>
    </fields>
    <label>Switch</label>
    <nameField>
        <label>Switch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Switch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SwitchControllerUnit.cls
public class SwitchControllerUnit {
    
    @AuraEnabled
    public static List<Switch__c> getSwitches(Id roomId) {
        System.debug('debug SwitchControllerUnit : getSwitches : roomId '+roomId);
        return [Select Id, Name , Room__c , isSwitchedOn__c , Wattage__c  From Switch__c Where Room__c = :roomId];
    }
    @AuraEnabled
    public static boolean setPowerOff(Id switchId)
    {
        try
        {
            System.debug('debug SwitchControllerUnit : setPowerOff : switchId '+switchId);
            List<Switch__c> switchList = [Select isSwitchedOn__c from Switch__c Where Id=:switchId limit 1];
            switchList[0].isSwitchedOn__c=false;
            update switchList;
            return true;
        }
        catch(Exception e)
        {
            // Log the executing class exception in a separate utility.
            System.debug('Exception : Occured In SwitchControllerUnit : setPowerOff ');
            return false;
        }
      }
    
    @AuraEnabled
    public static boolean setPowerOn(Id switchId)
    {
        try
        {
            List<Switch__c> switchList = [Select isSwitchedOn__c from Switch__c Where Id=:switchId limit 1];
            switchList[0].isSwitchedOn__c=true;
            update switchList;
            return true;
        }
        catch(Exception e)
        {
            // Log the executing class exception in a separate utility.
            System.debug('Exception : Occured In SwitchControllerUnit : setPowerOn ');
            return false;
        }
      }
    
}